function(myproject_enable_coverage project_name)
 if(NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(WARNING "Coverage is only available in Debug mode")
    return()
  endif()
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    target_compile_options(${project_name} INTERFACE --coverage)
    target_link_libraries(${project_name} INTERFACE --coverage)
  endif()
endfunction()
