name: build(Windows)
on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop

env:
  BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/62641e01-1e8d-4ace-91d6-ae03f7f8a71f/w_BaseKit_p_2024.0.0.49563_offline.exe
  HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/5b36181e-4974-4733-91c7-0c10c54900a5/w_HPCKit_p_2024.0.0.49588_offline.exe

jobs:
  Test:
    runs-on: windows-latest
    strategy:
      fail-fast: false

      # Recommendations:
      #   * support at least 2 operating systems
      #   * support at least 2 compilers
      #   * make sure all supported configurations for your project are built
      #
      # Disable/enable builds in this list to meet the above recommendations
      # and your own projects needs
      matrix:
        preset:
          - windows-msvc-debug
          - windows-msvc-release
          - windows-clang-debug
          - windows-clang-release

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get project name
        uses: cardinalby/export-env-action@v2
        with:
          envFile: ".github/constants.env"
      
      # TODO: use lists of compoents to install as the key
      # - name: Setup OneAPI cache
      #   id: setup_oneapi_cache
      #   uses: actions/cache@v4
      #   with:
      #     path: C:\Program Files (x86)\Intel\oneAPI
      #     key: oneapi-${{ runner.os }}-${{ env.BASEKIT_URL }}-${{ env.HPCKIT_URL }}

      - name: Install dependencies using chocolatey
        run: |
          choco install ccache
          choco install cppcheck
          choco install vswhere
          choco install opencppcoverage
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
        shell: powershell

      - name: Install Intel MPI
        # if: steps.setup_oneapi_cache.outputs.cache-hit != 'true'
        run: |
          curl.exe -o $env:TEMP\hpckit.exe --url ${{ env.HPCKIT_URL }}
          Start-Process -FilePath "$env:TEMP\hpckit.exe" -ArgumentList "-s -a --silent --eula accept --components intel.oneapi.win.mpi.devel" -NoNewWindow -Wait
        shell: powershell
      
      - name: Set Environment Variables
        run: |
          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
          echo %PATH% >> %GITHUB_PATH%
        shell: cmd

      - name: (Debug) Show Path
        run: |
          echo $env:PATH
        shell: powershell

      - name: Locate Visual Studio and CMake
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
          $cmakePath = Join-Path $vsPath "Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
          echo "CMAKE=$cmakePath" >> $env:GITHUB_ENV
        shell: powershell

      - name: Configure CMake
        run: |
          ${{ env.CMAKE }} -S . --preset ${{matrix.preset}} -DGIT_SHA:STRING=${{ github.sha }}
        shell: powershell

      - name: Build
        # Execute the build.
        run: |
          ${{ env.CMAKE }} --build --preset build-${{matrix.preset}}
        shell: powershell

      - name: Test
        if: ${{ !contains(matrix.preset, 'debug') }}
        run: |
          ctest --preset test-${{matrix.preset}}
        shell: powershell

      - name: Test & Coverage
        if: ${{ contains(matrix.preset, 'debug') }}
        run: |
          & "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe" --export_type cobertura:coverage.xml --cover_children --sources ${{ github.workspace }}\src --sources ${{ github.workspace }}\include -- ctest.exe --preset test-${{matrix.preset}}
        shell: powershell

      - name: Publish to codecov
        uses: codecov/codecov-action@v4
        if: ${{ contains(matrix.preset, 'debug') }}
        with:
          flags: ${{ runner.os }}
          name: ${{ runner.os }}-coverage
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
