name: build(Windows)
on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main
      - develop
      - "*" # For testing purposes

jobs:
  Test:
    runs-on: windows-latest
    strategy:
      fail-fast: false

      # Recommendations:
      #   * support at least 2 operating systems
      #   * support at least 2 compilers
      #   * make sure all supported configurations for your project are built
      #
      # Disable/enable builds in this list to meet the above recommendations
      # and your own projects needs
      matrix:
        preset:
          - windows-msvc-debug
          - windows-msvc-release
          - windows-clang-debug
          - windows-clang-release

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # TODO: Add caching with presets
      # - name: Setup Cache
      #   uses: ./.github/actions/setup_cache
      #   with:
      #     compiler: ${{ matrix.compiler }}
      #     build_type: ${{ matrix.build_type }}
      #     packaging_maintainer_mode: ${{ matrix.packaging_maintainer_mode }}
      #     generator: ${{ matrix.generator }}

      - name: Get project name
        uses: cardinalby/export-env-action@v2
        with:
          envFile: ".github/constants.env"

      - name: (Debug) Print Path
        run: |
          echo $env:Path
        shell: pwsh

      - name: Install dependencies
        run: |
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          choco install visualstudio2022buildtools --package-parameters "--config $env:GITHUB_WORKSPACE/.vsconfig"
          $clpath = vswhere -products * -latest -prerelease -find **/Hostx64/x64/*
          $clangpath = vswhere -products * -latest -prerelease -find **/Llvm/bin/*
          $vcvarsallpath =  vswhere -products * -latest -prerelease -find **/Auxiliary/Build/*
          $path = [System.Environment]::GetEnvironmentVariable("PATH", "User")
          [Environment]::SetEnvironmentVariable("Path", $path + ";$clpath" + ";$clangpath" + ";$vcvarsallpath", "User")
          refreshenv
          choco install ccache
          choco install cppcheck
          choco install opencppcoverage
        shell: pwsh

      - name: Configure CMake
        run: |
          cmake -S . -B ./build --preset ${{matrix.preset}} -D${{ env.PROJECT_NAME }}_ENABLE_COVERAGE:BOOL=${{ contains(matrix.preset,'debug') }} -DGIT_SHA:STRING=${{ github.sha }}
        shell: pwsh

      - name: Build
        # Execute the build.
        run: |
          cmake --build ./build
        shell: pwsh

      - name: Windows - Test and coverage
        working-directory: ./build
        run: |
          OpenCppCoverage.exe --export_type cobertura:coverage.xml --cover_children -- ctest --preset ${{matrix.preset}}
        shell: pwsh

      - name: Publish to codecov
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ runner.os }}
          name: ${{ runner.os }}-coverage
          files: ./build/coverage.xml
